### ISSUE TITLE
HOL - Guided - found errors

### ISSUE THREAD

**Issue by iBoonz** [Microsoft/MCW-Azure-Blockchain#12]
Hi,

Just went through the lab, very intresting, thanks for the effort creating this!

Task 2 --> Section 2 --> Missing **]**
Task 2 --> Section 6 --> "AllowedRoles": ["Admin"] --> Due to this role the users can't create a new contract or take action. Propose to add the role "user" to the AllowedRoles

**Comment by crpietschmann** [comment]
Thank for the PR, it's been merged and these issues have been fixed in latest pending update.
