### ISSUE TITLE
Deployment failure

### ISSUE THREAD

**Issue by awsiotdemo** [Microsoft/MCW-Azure-Blockchain#16]
I did everything as per the hand on lab. But while running deployment everytime I am getting error that App builder and Azure blckcin failed.

Code Error - Deployment Failed.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"message\": \"Subscription is disabled. CorrelationId: c858c147-8e47-4505-b282-7d1f799a9437\",\r\n \"code\": \"BadRequest\"\r\n }\r\n}"}]}

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"DeploymentFailed\\\",\\r\\n \\\"message\\\": \\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"BadRequest\\\",\\r\\n \\\"message\\\": \\\"{\\\\r\\\\n \\\\\\\"error\\\\\\\": {\\\\r\\\\n \\\\\\\"message\\\\\\\": \\\\\\\"Subscription is disabled. CorrelationId: c858c147-8e47-4505-b282-7d1f799a9437\\\\\\\",\\\\r\\\\n \\\\\\\"code\\\\\\\": \\\\\\\"BadRequest\\\\\\\"\\\\r\\\\n }\\\\r\\\\n}\\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"BadRequest\",\r\n \"message\": \"{\\r\\n \\\"error\\\": {\\r\\n \\\"message\\\": \\\"Subscription is disabled. CorrelationId: c858c147-8e47-4505-b282-7d1f799a9437\\\",\\r\\n \\\"code\\\": \\\"BadRequest\\\"\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by hkamel** [comment]
Hello @awsiotdemo, according to the error message it seems that the subscription you are using to deploy the solution is disabled `Subscription is disabled` which can be due to many reasons check [Why is my Azure subscription disabled and how do I reactivate it?
](https://docs.microsoft.com/en-us/azure/billing/billing-subscription-become-disable)

Try to change the subscription if you have access to an active one.

**Comment by awsiotdemo** [comment]
thanks @hkamel. Yeah that could be the reason. I am testing with another subscription. Will post the success or failure :+1:

**Comment by hkamel** [comment]
@awsiotdemo did you managed to solve this?

**Comment by crpietschmann** [comment]
This error isn't anything with the lab. Appears to be a Subscription issue.
