### ISSUE TITLE
Readme.MD - Text Corrections - Hands-On Lab section

### ISSUE THREAD

**Issue by venuvedam** [Microsoft/MCW-Azure-Blockchain#23]
Comment: "You will do this using Ethereum Blockchain with the use of Smart Contracts to collect device telemetry information in addition to enforce contract specifics related to conditions during transport of goods. Specifically, the IoT devices will report temperature and humidity data that will be validated through the Smart Contracts against agreed upon acceptable ranges."

**Observation**
	
This whole paragraph in Hands-on Lab section is a verbatim reproduction of the paragraph just before it in Whiteboard design session section. Please reword. 
	
Same observation about the next paragraph as well in Hands on Lab section.

**Comment by crpietschmann** [comment]
There is some duplication between the Lab and Whiteboard by design. The Lab extends the Whiteboard session with hands-on learning exercises. Also, they are designed to be able to be delivered separately if desired.
