### ISSUE TITLE
WDS Student Guide - Customer Needs

### ISSUE THREAD

**Issue by venuvedam** [Microsoft/MCW-Azure-Blockchain#25]
The following statement in Customer Needs section is interesting.

"The Blockchain implementation needs to be secure and fully under the control of Northwind Traders; while simultaneously integrating with partners and third-parties when managing the supply chain."

It says the blockchain ledger needs to be "fully under the control of Northwind Traders". The USP of blockchain is that it is shared ledger among the participants. Ideally there should not be any one Super User or Super Admin of the ledger (One node being "more equal" than the others) for the idea to work. Otherwise, it is just a data store that other participants on the supply chain "choose" to trust. If the blockchain is completely in NW's control, I don't see how it makes sense for its suppliers and partners as a shared ledger that no one organization has complete control on.

Thoughts?

**Comment by crpietschmann** [comment]
The Blockchain Workbench as it deploys from the Azure Portal is fully under control of Northwind Traders. Do you have suggestions on how to modify the workshop to integrate third-party controlled nodes into the blockchain ledger solution that gets deployed?

**Comment by venuvedam** [comment]
I guess till multi-sub feature is supported by workbench, we will have to go with the private chain model (One org controls all resources).
