### ISSUE TITLE
WDS Trainer Presentation

### ISSUE THREAD

**Issue by venuvedam** [Microsoft/MCW-Azure-Blockchain#27]
Depending on the status of the previous observations I raised, the text on the presentation also needs to change. 

Also, in the last slide there is a quote from the customer who is very much satisfied with our solution. :) Can we include quotes from one of the suppliers and also the auditor? Blockchain makes everyone happy, doesn't it? 👍

**Comment by crpietschmann** [comment]
The standard format for the WDS is to have a single customer quote at the end of the presentation.
