### ISSUE TITLE
Hands-On-Lab, Ex 1, Task 2: Create App Registration

### ISSUE THREAD

**Issue by eiriniasteri** [Microsoft/MCW-Azure-Blockchain#35]
Task 2 "Create App Registration" in Exercise 1 is missing. 
Can you please post it?

Thank you.

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann 
Hi Chris, please add missing task in hands-on lab and assign it to me to merge & update HTML.
Thanks,
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Hi Paul!  Jeff said you are handling this one so I've assigned it to you.
Thanks, Dawnmarie

**Comment by paulopsgility** [comment]
This is actually not a missing task. The MCW was updated to use the automated script that the Blockchain Workbench supports now. The "missing step" is now in Exercise 2, Task 4: Setup Azure AD Configuration. 

The table of contents is out of sync though.

**Comment by paulopsgility** [comment]
Updated ToC

**Comment by crpietschmann** [comment]
@paulopsgility I believe this is correct. it matches my recollection of the MCW since I last touched it.
