### ISSUE TITLE
WDS - trainer presentation

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Azure-Blockchain#5]
Slide 9 & 23 - Customer objections.  First objection starts "There's tons of buzz about..."  I'm not sure that phrase will translate to different regions/languages.  Please re-phrase.
Slide 11 - Image but no presenter/trainer notes.  Is that correct?
Slide 12 - Same as above
Slide 19 - No presenter/trainer notes?

**Comment by crpietschmann** [comment]
These changes have been made.
