### ISSUE TITLE
WDS trainer & student guide

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Azure-Blockchain#7]
1st customer objection says "There's tons of buzz about Blockchain,"  Not sure that will translate to other regions/languages.  Please re-phrase.

**Comment by crpietschmann** [comment]
Reworded the use of "tons of buzz about" to be "a lot of popular interest in" to re-phrase it for easier understanding in other regions/languages.

This is part of commit https://github.com/Microsoft/MCW-Azure-Blockchain/commit/f12f836960db70149b95fb4ea512bcc5779e0325
