### ISSUE TITLE
WDS trainer guide

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Azure-Blockchain#8]
Design a Blockchain solution section.  You have 1 - 4 listed.  Design the IoT device and sensor integration there is 1 - 3 listed.

In the preferred solution section, those numbers are not addressed.  The answers are text only and it's hard to tell if each of the issues in the student guide are answered in the trainer guide.  Can the answers match the formatting of the questions asked?

**Comment by crpietschmann** [comment]
The "Design the Blockchain Solution" and "Design the IoT (Internet of Things) device and sensor integration** sections have both been restructured so the answers in the trainer guide match up with the questions in the student guide.

This has been updated in commit https://github.com/Microsoft/MCW-Azure-Blockchain/commit/853fb234d8cacf6625cb9f84857351f7d5e1af99
